[package]
name = "LayerN"
version = "0.1.0"
edition = "2021"

[dependencies]
mimc-rs = "0.0.2"
ark-ff = "0.4.0"
ark-bls12-381 = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
num-bigint = "0.4"
plonky2 = "1.0.2"
